project:
  type: book
  output-dir: docs

book:
  title: "Foundations of Data Science"
  author: "Harmony Luce"
  date: today
  repo-url: https://github.com/[YOURACCOUNT]/[YOURREPO]
  repo-branch: main
  repo-actions: [source, edit, issue]
  chapters:
    - index.qmd
    - rstudio_and_data.qmd
    - probability.qmd
    - comprequiz.qmd
  
format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    toc: true
    css: styles/styles.css
    include-in-header:
      text: |
        <style>
        #quarto-sidebar .menu-text {
          display: flex;
        }
        #quarto-sidebar .chapter-number {
          display: block;
          width: 1em;
          text-align: left;
        }
        #quarto-sidebar .chapter-title {
          display: block;
          padding-left: 10px;
          text-indent: -10px;
          width: 100%;
        }
        </style>
    # highlight-style: styles/joyce.theme
    # include-after-body:
    #   - scripts/quiz.js
    # callout-icon: false
    
# [default, styles/edav3.scss]
# bibliography: references.bib    
    
knitr:
  opts_chunk: 
    fig.align: center
    out.width: 70%
    
execute:
  echo: true
  warning: false
  message: false
  error: true
  cache: true

editor: source




