project:
  type: book
  output-dir: docs

book:
  title: "Foundations of Data Science"
  author: "Harmony Luce"
  date: today
  repo-url: https://github.com/[YOURACCOUNT]/[YOURREPO]
  repo-branch: main
  repo-actions: [source, edit, issue]
  chapters:
    - index.qmd
    - rstudio_and_data.qmd
    - probability.qmd
    - summary.qmd
  
format:
  html:
    theme: 
      light: zephyr
      dark: vapor
    toc: true
    highlight-style: styles/joyce.theme
    css: styles/styles.css
    include-after-body:
      - scripts/quiz.js
    callout-icon: false
    
# [default, styles/edav3.scss]
# bibliography: references.bib    
    
knitr:
  opts_chunk: 
    fig.align: center
    out.width: 70%
    
execute:
  echo: true
  warning: false
  message: false
  error: true
  cache: true

editor: source




